// const apiUrl = "http://192.168.3.152:5005/"; ////local
// const apiUrl = "http://52.15.253.94:3000/"; ////live
// const apiUrl = "http://18.219.253.106:3000/"; ////live new

// Api Action type constants
const userApiConstants = {
  // Clear state
  CLEAR_STATE: "CLEAR_STATE",
  // To Handle concert tabs
  HANDLE_CONCERTS_TAB_STATE: "HANDLE_CONCERTS_TAB_STATE",
  // Handle side navigation
  HANDLE_SIDEBAR_NAVIGATION_STATE: "HANDLE_SIDEBAR_NAVIGATION_STATE",
  HANDLE_SIDEBAR_DRAWER_TOGGLE_STATE: "HANDLE_SIDEBAR_DRAWER_TOGGLE_STATE",

  // ************ AUTHENTICATION ADMIN************
  // Authentications types
  API_AUTHENTICATION_FAILED: "API_AUTHENTICATION_FAILED",
  API_AUTHENTICATION_ERROR: "API_AUTHENTICATION_ERROR",

  // Login
  API_USER_LOGIN_LOAD: "API_USER_LOGIN_LOAD",
  API_USER_LOGIN_SUCCESS: "API_USER_LOGIN_SUCCESS",
  API_USER_LOGIN_FAILED: "API_USER_LOGIN_FAILED",
  API_USER_LOGIN_ERROR: "API_USER_LOGIN_ERROR",

  // get user access token
  API_GET_USER_ACCESS_TOKEN_LOAD: "API_GET_USER_ACCESS_TOKEN_LOAD",
  API_GET_USER_ACCESS_TOKEN_SUCCESS: "API_GET_USER_ACCESS_TOKEN_SUCCESS",
  API_GET_USER_ACCESS_TOKEN_FAILED: "API_GET_USER_ACCESS_TOKEN_FAILED",
  API_GET_USER_ACCESS_TOKEN_ERROR: "API_GET_USER_ACCESS_TOKEN_ERROR",

  // list user games
  API_GET_USER_GAMES_LIST_LOAD: "API_GET_USER_GAMES_LIST_LOAD",
  API_GET_USER_GAMES_LIST_SUCCESS: "API_GET_USER_GAMES_LIST_SUCCESS",
  API_GET_USER_GAMES_LIST_FAILED: "API_GET_USER_GAMES_LIST_FAILED",
  API_GET_USER_GAMES_LIST_ERROR: "API_GET_USER_GAMES_LIST_ERROR",

  // change password
  API_CHANGE_USER_PASSWORD_LOAD: "API_CHANGE_USER_PASSWORD_LOAD",
  API_CHANGE_USER_PASSWORD_SUCCESS: "API_CHANGE_USER_PASSWORD_SUCCESS",
  API_CHANGE_USER_PASSWORD_FAILED: "API_CHANGE_USER_PASSWORD_FAILED",
  API_CHANGE_USER_PASSWORD_ERROR: "API_CHANGE_USER_PASSWORD_ERROR",

  // list all games
  API_GET_USER_ALL_GAMES_LOAD: "API_GET_USER_ALL_GAMES_LOAD",
  API_GET_USER_ALL_GAMES_SUCCESS: "API_GET_USER_ALL_GAMES_SUCCESS",
  API_GET_USER_ALL_GAMES_FAILED: "API_GET_USER_ALL_GAMES_FAILED",
  API_GET_USER_ALL_GAMES_ERROR: "API_GET_USER_ALL_GAMES_ERROR",

  // update game point
  API_UPDATE_GAME_POINTS_LOAD: "API_UPDATE_GAME_POINTS_LOAD",
  API_UPDATE_GAME_POINTS_SUCCESS: "API_UPDATE_GAME_POINTS_SUCCESS",
  API_UPDATE_GAME_POINTS_FAILED: "API_UPDATE_GAME_POINTS_FAILED",
  API_UPDATE_GAME_POINTS_ERROR: "API_UPDATE_GAME_POINTS_ERROR",
};

export { userApiConstants };
