// const apiUrl = "http://192.168.3.152:5005/"; ////local
// const apiUrl = "http://52.15.253.94:3000/"; ////live
// const apiUrl = "http://18.219.253.106:3000/"; ////live new

// Api Action type constants
const apiConstants = {
  // Clear state
  CLEAR_STATE: "CLEAR_STATE",
  // To Handle concert tabs
  HANDLE_CONCERTS_TAB_STATE: "HANDLE_CONCERTS_TAB_STATE",
  // Handle side navigation
  HANDLE_SIDEBAR_NAVIGATION_STATE: "HANDLE_SIDEBAR_NAVIGATION_STATE",
  HANDLE_SIDEBAR_DRAWER_TOGGLE_STATE: "HANDLE_SIDEBAR_DRAWER_TOGGLE_STATE",

  // add checkbox
  API_ADD_BAND_EDIT_CHECKBOX: "API_ADD_BAND_EDIT_CHECKBOX",

  // clear added news
  CLEAR_ADDED_NEWS: "CLEAR_ADDED_NEWS",
  // ************ DASHBOARD ADMIN************
  API_GET_DASHBOARD_DETAILS_LOAD: "API_GET_DASHBOARD_DETAILS_LOAD",
  API_GET_DASHBOARD_DETAILS_SUCCESS: "API_GET_DASHBOARD_DETAILS_SUCCESS",
  API_GET_DASHBOARD_DETAILS_FAILED: "API_AUTHENTICATION_FAILED",
  API_GET_DASHBOARD_DETAILS_ERROR: "API_AUTHENTICATION_ERROR",

  // ************ AUTHENTICATION ADMIN************
  // Authentications types
  API_AUTHENTICATION_FAILED: "API_AUTHENTICATION_FAILED",
  API_AUTHENTICATION_ERROR: "API_AUTHENTICATION_ERROR",

  // Login
  API_LOGIN_LOAD: "API_LOGIN_LOAD",
  API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",

  // User list
  API_GET_USER_LIST_LOAD: "API_GET_USER_LIST_LOAD",
  API_GET_USER_LIST_SUCCESS: "API_GET_USER_LIST_SUCCESS",
  API_GET_USER_LIST_FAILED: "API_GET_USER_LIST_FAILED",
  API_GET_USER_LIST_ERROR: "API_GET_USER_LIST_ERROR",

  // Add user
  API_ADD_USER_LOAD: "API_ADD_USER_LOAD",
  API_ADD_USER_SUCCESS: "API_ADD_USER_SUCCESS",
  API_ADD_USER_FAILED: "API_ADD_USER_FAILED",
  API_ADD_USER_ERROR: "API_ADD_USER_ERROR",

  // edit user
  API_EDIT_USER_LOAD: "API_EDIT_USER_LOAD",
  API_EDIT_USER_SUCCESS: "API_EDIT_USER_SUCCESS",
  API_EDIT_USER_FAILED: "API_EDIT_USER_FAILED",
  API_EDIT_USER_ERROR: "API_EDIT_USER_ERROR",

  // block/unblock user
  API_USER_BLOCK_STATUS_LOAD: "API_USER_BLOCK_STATUS_LOAD",
  API_USER_BLOCK_STATUS_SUCCESS: "API_USER_BLOCK_STATUS_SUCCESS",
  API_USER_BLOCK_STATUS_FAILED: "API_USER_BLOCK_STATUS_FAILED",
  API_USER_BLOCK_STATUS_ERROR: "API_USER_BLOCK_STATUS_ERROR",

  // add games
  API_ADD_GAMES_LOAD: "API_ADD_GAMES_LOAD",
  API_ADD_GAMES_SUCCESS: "API_ADD_GAMES_SUCCESS",
  API_ADD_GAMES_FAILED: "API_ADD_GAMES_FAILED",
  API_ADD_GAMES_ERROR: "API_ADD_GAMES_ERROR",

  // get games list
  API_GET_GAMES_LIST_LOAD: "API_GET_GAMES_LIST_LOAD",
  API_GET_GAMES_LIST_SUCCESS: "API_GET_GAMES_LIST_SUCCESS",
  API_GET_GAMES_LIST_FAILED: "API_GET_GAMES_LIST_FAILED",
  API_GET_GAMES_LIST_ERROR: "API_GET_GAMES_LIST_ERROR",

  // Update Admin Profile
  API_UPDATE_ADMIN_PROFILE_LOAD: "API_UPDATE_ADMIN_PROFILE_LOAD",
  API_UPDATE_ADMIN_PROFILE_SUCCESS: "API_UPDATE_ADMIN_PROFILE_SUCCESS",
  API_UPDATE_ADMIN_PROFILE_FAILED: "API_UPDATE_ADMIN_PROFILE_FAILED",
  API_UPDATE_ADMIN_PROFILE_ERROR: "API_UPDATE_ADMIN_PROFILE_ERROR",

  
};

export { apiConstants };
